-- Create a table to store column renaming rules based on the original header
create table public.column_rules (
  id bigint generated by default as identity primary key,
  original_header text not null,     -- The header name exactly as it appears in the DBF file
  new_header text not null,          -- The new name the user gave to this header
  is_visible boolean default true,   -- Whether this column should be included in the Excel output
  position_index integer default 0,  -- The relative order representation (optional, might just use simple integer)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Ensure that each original_header has only one rule configured
  constraint unique_original_header unique (original_header)
);

-- Add some Row Level Security (RLS) policies if needed
-- Since there is no auth requested right now, we can allow anonymous access for ease of use, 
-- but it's recommended to lock this down later.
alter table public.column_rules enable row level security;

create policy "Allow public read access"
  on public.column_rules
  for select
  using (true);

create policy "Allow public insert access"
  on public.column_rules
  for insert
  with check (true);

create policy "Allow public update access"
  on public.column_rules
  for update
  using (true);

-- Function to automatically update the updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_column_rules_updated_at
    before update on public.column_rules
    for each row
    execute procedure update_updated_at_column();
